In [ ]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 6, 4, 5])

In [ ]:
arr[::-1]


array([5, 4, 6, 3, 2, 1])

In [ ]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])

In [ ]:
print("Flattened array using flatten() ",array1.flatten())

Flattened array using flatten()  [1 2 3 2 4 5 1 2 3]


In [ ]:
print("Flattened array using ravel() ",array1.ravel())

Flattened array using ravel()  [1 2 3 2 4 5 1 2 3]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

In [ ]:
arr_check = np.array_equal(arr1, arr2)
if arr_check:
    print("Arrays are equal")
else:
    print("Arrays are not equal")

Arrays are equal


In [ ]:
x = np.array([1,2,3,4,5,1,2,1,1,1])

In [ ]:
count = np.bincount(x)
freq = np.argmax(count)
ind = np.where(x == freq)[0]
print("Most frequent number is: ",freq)
print("Indices of number is: ",ind)

Most frequent number is:  1
Indices of number is:  [0 5 7 8 9]


In [ ]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

In [ ]:
count = np.bincount(y)
max = np.max(count)
freq = np.where(count == max)[0]
ind = {val: np.where(y == val)[0] for val in freq}

In [ ]:
print("Frequency: ", freq)
print("Indices: ", ind)

Frequency:  [1 3]
Indices:  {1: array([0, 1, 2]), 3: array([4, 8, 9])}


In [ ]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

In [ ]:
arr = np.array(gfg)
print(arr)

[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]


In [ ]:
arr.sum()

45

In [ ]:
arr.sum(axis = 1)

array([14, 16, 15])

In [ ]:
arr.sum(axis = 0)

array([20,  9, 16])

In [ ]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])

In [ ]:
print(n_array)

[[55 25 15]
 [30 44  2]
 [11 45 77]]


In [ ]:
diagonal_elements = np.diagonal(n_array)

In [ ]:
d_sum = np.sum(diagonal_elements)
print(d_sum)

176


In [ ]:
e_val = np.linalg.eigvals(n_array)
print(e_val)

[98.16835147 28.097044   49.73460452]


In [ ]:
_, e_vec = np.linalg.eig(n_array)
print(e_vec)

[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]


In [ ]:
print("Inverse of matrix is: ")
print(np.linalg.inv(n_array))

Inverse of matrix is: 
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]


In [ ]:
print("Determinant of matrix is: ",np.linalg.det(n_array))

Determinant of matrix is:  137180.0000000001


In [ ]:
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])

In [ ]:
mult = np.dot(p,q)
print(mult)

[[16 19]
 [26 31]]


In [ ]:
pf = p.flatten()

In [ ]:
qf = q.flatten()

In [ ]:
cov = np.cov(pf,qf)
print(cov)

[[0.66666667 1.        ]
 [1.         1.66666667]]


In [ ]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

In [ ]:
inner_join = np.dot(x,y.T)
print(inner_join)

[[17 52]
 [13 62]]


In [ ]:
print(np.outer(x.flatten(),y.flatten()))

[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]


In [ ]:
print(np.cross(x,y))

[[-20   4   7]
 [-84  36  20]]


In [ ]:
x_flat = x.flatten()
y_flat = y.flatten()
meshy = np.meshgrid(x_flat,y_flat)
combine = np.array(meshy)
transpose = combine.T
cart_product = transpose.reshape(-1, 2)
print(cart_product)

[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [ ]:
array = np.array([[1, -2, 3],[-4, 5, -6]])

In [ ]:
print(np.abs(array))

[[1 2 3]
 [4 5 6]]


In [ ]:
print("Percentile of flattened array = ",np.percentile(array.flatten(), [25, 50, 75]))
print("Percentile for each row = ",np.percentile(array, [25, 50, 75], axis = 1))
print("Percentile for each column = ",np.percentile(array, [25, 50, 75], axis = 0))

Percentile of flattened array =  [-3.5 -0.5  2.5]
Percentile for each row =  [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Percentile for each column =  [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]


In [ ]:
print("Mean of flattened array = ",np.mean(array.flatten()))
print("Mean for each row = ",np.mean(array, axis = 1))
print("Mean for each column = ",np.mean(array, axis = 0))

Mean of flattened array =  -0.5
Mean for each row =  [ 0.66666667 -1.66666667]
Mean for each column =  [-1.5  1.5 -1.5]


In [ ]:
print("Median of flattened array = ", np.median(array.flatten()))
print("Median for each row = ",np.median(array, axis = 1))
print("Median for each column = ",np.median(array, axis = 0))

Median of flattened array =  -0.5
Median for each row =  [ 1. -4.]
Median for each column =  [-1.5  1.5 -1.5]


In [ ]:
print("Standard Deviation of flattened array = ",np.std(array.flatten()))
print("Standard Deviation for each row = ",np.std(array, axis = 1))
print("Standard Deviation for each column = ",np.std(array, axis = 0))

Standard Deviation of flattened array =  3.8622100754188224
Standard Deviation for each row =  [2.05480467 4.78423336]
Standard Deviation for each column =  [2.5 3.5 4.5]


In [ ]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])

In [ ]:
print("Floor of array = ", np.floor(a))
print("Ceil of array = ", np.ceil(a))
print("Truncated values of array = ", np.trunc(a))
print("Rounded Values of array = ", np.round(a))

Floor of array =  [-2. -2. -1.  0.  1.  1.  3.]
Ceil of array =  [-1. -1. -0.  1.  2.  2.  3.]
Truncated values of array =  [-1. -1. -0.  0.  1.  1.  3.]
Rounded Values of array =  [-2. -2. -0.  0.  2.  2.  3.]


In [ ]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

In [ ]:
sorte = sorted(array)

In [ ]:
print(sorte)

[10, 16, 16, 52, 54, 62, 453]


In [ ]:
for x in sorte:
  print(sorte.index(x))

0
1
1
3
4
5
6


In [ ]:
smallest_elements = np.partition(array, 4)[:4]
print("4 smallest elements:", smallest_elements)

4 smallest elements: [16 10 16 52]


In [ ]:
largest_elements = np.partition(array, -5)[-5:]
print("5 largest elements:", largest_elements)

5 largest elements: [ 16  52  54  62 453]


In [ ]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

In [ ]:
print(array[array==array.astype(int)])

[1. 2. 3. 2.]


In [ ]:
print(array[array!=array.astype(int)])

[1.2 2.2]


In [ ]:
pip install pillow

In [ ]:
from PIL import Image

In [ ]:
import os

In [ ]:
from PIL import Image
import numpy as np

def img_to_array(path, save_path):
    # Open the image
    img = Image.open(path)

    # Convert the image to a NumPy array
    img_array = np.array(img)

    # Save the array to a text file
    np.savetxt(save_path, img_array.reshape(-1, img_array.shape[2] if img_array.ndim == 3 else 1), fmt='%d', delimiter=',')

    print(f'Image data saved to {save_path}')

# Example usage
img_to_array('/content/dog.jpeg', 'saved_image_data.txt')

Image data saved to saved_image_data.txt


In [ ]:
import numpy as np
from PIL import Image
import os

def load_array(file_path):
    try:
        # Check if file exists
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"{file_path} does not exist")

        # Load the image data
        img_array = np.loadtxt(file_path, dtype=int, delimiter=',')

        # Debugging: Print array size and shape
        print(f"Array size: {img_array.size}")
        print(f"Array shape: {img_array.shape}")

        # The image array is in shape (num_pixels, 3) for RGB
        num_pixels = img_array.shape[0]

        # Calculate possible dimensions
        possible_dims = []
        for height in range(1, int(np.sqrt(num_pixels)) + 1):
            if num_pixels % height == 0:
                width = num_pixels // height
                possible_dims.append((height, width))

        # Check possible dimensions to find a suitable one
        for height, width in possible_dims:
            try:
                if num_pixels == height * width * 3:
                    img_array = img_array.reshape((height, width, 3))
                    mode = 'RGB'
                    img = Image.fromarray(np.uint8(img_array), mode)
                    return img
            except Exception as e:
                print(f"Failed to reshape to {height}x{width}x3: {e}")

        raise ValueError("Could not determine suitable dimensions for reshaping")

    except Exception as e:
        print(f"An error occurred: {e}")
        return None

# Example usage
img = load_array('saved_image_data.txt')  # Adjust the filename based on your saved file
if img:
    img.show()
else:
    print("No image to show")


Array size: 898704
Array shape: (299568, 3)
An error occurred: Could not determine suitable dimensions for reshaping
No image to show
